import { Product, Review, BlogPost, Testimonial, FAQItem, Category } from '@/types';

export const categories: Category[] = [
  { name: 'Rings', slug: 'rings', image: 'https://images.pexels.com/photos/31728371/pexels-photo-31728371.jpeg?auto=compress&cs=tinysrgb&w=600', count: 48 },
  { name: 'Bangles', slug: 'bangles', image: 'https://images.pexels.com/photos/37485307/pexels-photo-37485307.jpeg?auto=compress&cs=tinysrgb&w=600', count: 36 },
  { name: 'Bracelets', slug: 'bracelets', image: 'https://images.pexels.com/photos/3641056/pexels-photo-3641056.jpeg?auto=compress&cs=tinysrgb&w=600', count: 24 },
  { name: 'Anklets', slug: 'anklets', image: 'https://images.pexels.com/photos/20626511/pexels-photo-20626511.jpeg?auto=compress&cs=tinysrgb&w=600', count: 18 },
  { name: 'Necklaces', slug: 'necklaces', image: 'https://images.pexels.com/photos/5820156/pexels-photo-5820156.jpeg?auto=compress&cs=tinysrgb&w=600', count: 42 },
  { name: 'Chains', slug: 'chains', image: 'https://images.pexels.com/photos/3641059/pexels-photo-3641059.jpeg?auto=compress&cs=tinysrgb&w=600', count: 30 },
  { name: 'Pendants', slug: 'pendants', image: 'https://images.pexels.com/photos/36650259/pexels-photo-36650259.jpeg?auto=compress&cs=tinysrgb&w=600', count: 22 },
  { name: 'Earrings', slug: 'earrings', image: 'https://images.pexels.com/photos/10976654/pexels-photo-10976654.jpeg?auto=compress&cs=tinysrgb&w=600', count: 38 },
  { name: 'Temple Jewelry', slug: 'temple-jewelry', image: 'https://images.pexels.com/photos/37485302/pexels-photo-37485302.jpeg?auto=compress&cs=tinysrgb&w=600', count: 16 },
  { name: 'Bridal Collection', slug: 'bridal-collection', image: 'https://images.pexels.com/photos/19021379/pexels-photo-19021379.jpeg?auto=compress&cs=tinysrgb&w=600', count: 28 },
  { name: "Men's Jewelry", slug: 'mens-jewelry', image: 'https://images.pexels.com/photos/37485309/pexels-photo-37485309.jpeg?auto=compress&cs=tinysrgb&w=600', count: 14 },
  { name: 'Kids Collection', slug: 'kids-collection', image: 'https://images.pexels.com/photos/8886971/pexels-photo-8886971.jpeg?auto=compress&cs=tinysrgb&w=600', count: 12 },
];

const img = (id: number) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=800`;

export const products: Product[] = [
  {
    id: '1',
    slug: 'eternal-diamond-solitaire-ring',
    name: 'Eternal Diamond Solitaire Ring',
    category: 'Rings',
    categorySlug: 'rings',
    description: 'A breathtaking solitaire diamond ring crafted in 18K gold.',
    longDescription:
      'The Eternal Diamond Solitaire Ring features a brilliant-cut certified diamond set in premium 18K gold. Each piece is handcrafted by master artisans, ensuring unparalleled brilliance and fire. The solitaire setting maximizes light return, creating a mesmerizing sparkle that captures every gaze.',
    price: 125000,
    originalPrice: 150000,
    images: [img(31728371), img(12290109), img(5737285), img(30541185)],
    metal: '18K Gold',
    purity: '18K (750)',
    stone: 'Natural Diamond',
    weight: '4.5g',
    certification: 'GIA Certified',
    warranty: 'Lifetime',
    stock: 5,
    rating: 4.9,
    reviewCount: 128,
    gender: 'Women',
    occasion: ['Wedding', 'Engagement', 'Anniversary'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    hasSizeGuide: true,
    sizeGuideType: 'ring',
    highlights: ['GIA Certified Diamond', '18K Hallmarked Gold', 'Lifetime Warranty', 'Free Insured Shipping'],
  },
  {
    id: '2',
    slug: 'royal-gold-temple-necklace',
    name: 'Royal Gold Temple Necklace',
    category: 'Necklaces',
    categorySlug: 'necklaces',
    description: 'Traditional temple necklace in 22K gold with intricate detailing.',
    longDescription:
      'The Royal Gold Temple Necklace is a masterpiece of South Indian craftsmanship. Handcrafted in 22K gold, it features traditional temple motifs inspired by ancient architecture. Each pendant is meticulously detailed, making it a perfect heirloom piece for weddings and festivals.',
    price: 285000,
    originalPrice: 320000,
    images: [img(5820156), img(37485302), img(36650259), img(15622999)],
    metal: '22K Gold',
    purity: '22K (916)',
    stone: 'None',
    weight: '32g',
    certification: 'BIS Hallmarked',
    warranty: 'Lifetime',
    stock: 3,
    rating: 5.0,
    reviewCount: 64,
    gender: 'Women',
    occasion: ['Wedding', 'Festival', 'Traditional'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    hasSizeGuide: true,
    sizeGuideType: 'necklace',
    highlights: ['22K Hallmarked Gold', 'Traditional Temple Design', 'Heirloom Quality', 'Handcrafted'],
  },
  {
    id: '3',
    slug: 'bridal-kundan-bangle-set',
    name: 'Bridal Kundan Bangle Set',
    category: 'Bangles',
    categorySlug: 'bangles',
    description: 'Exquisite Kundan bangle set for the modern bride.',
    longDescription:
      'The Bridal Kundan Bangle Set features eight intricately designed bangles adorned with Kundan stones and meenakari work. Crafted in 22K gold, this set is the perfect complement to your bridal ensemble, blending traditional artistry with contemporary elegance.',
    price: 195000,
    images: [img(37485307), img(37485309), img(8887000), img(20626511)],
    metal: '22K Gold',
    purity: '22K (916)',
    stone: 'Kundan',
    weight: '48g',
    certification: 'BIS Hallmarked',
    warranty: 'Lifetime',
    stock: 7,
    rating: 4.8,
    reviewCount: 92,
    gender: 'Women',
    occasion: ['Wedding', 'Bridal'],
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    hasSizeGuide: true,
    sizeGuideType: 'bangle',
    highlights: ['Set of 8 Bangles', 'Kundan & Meenakari Work', '22K Hallmarked Gold', 'Bridal Special'],
  },
  {
    id: '4',
    slug: 'pearl-drop-earrings',
    name: 'Pearl Drop Earrings',
    category: 'Earrings',
    categorySlug: 'earrings',
    description: 'Elegant freshwater pearl drop earrings in 18K gold.',
    longDescription:
      'These Pearl Drop Earrings combine lustrous freshwater pearls with delicate 18K gold settings. The timeless design transitions effortlessly from day to evening, making them a versatile addition to any jewelry collection.',
    price: 45000,
    originalPrice: 55000,
    images: [img(10976654), img(5737290), img(9429425), img(11365012)],
    metal: '18K Gold',
    purity: '18K (750)',
    stone: 'Freshwater Pearl',
    weight: '6g',
    certification: 'BIS Hallmarked',
    warranty: '5 Years',
    stock: 15,
    rating: 4.7,
    reviewCount: 156,
    gender: 'Women',
    occasion: ['Casual', 'Party', 'Gift'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    hasSizeGuide: true,
    sizeGuideType: 'earring',
    highlights: ['Freshwater Pearls', '18K Gold Setting', 'Lightweight Design', 'Versatile Style'],
  },
  {
    id: '5',
    slug: 'temple-jewelry-jhumka-set',
    name: 'Temple Jewelry Jhumka Set',
    category: 'Temple Jewelry',
    categorySlug: 'temple-jewelry',
    description: 'Traditional temple jhumka earrings with matching necklace.',
    longDescription:
      'The Temple Jewelry Jhumka Set includes stunning jhumka earrings and a matching necklace, crafted in 22K gold with traditional temple motifs. This set embodies the rich cultural heritage of South Indian jewelry making.',
    price: 165000,
    images: [img(37485302), img(5820156), img(36650259), img(15622999)],
    metal: '22K Gold',
    purity: '22K (916)',
    stone: 'Ruby & Emerald',
    weight: '28g',
    certification: 'BIS Hallmarked',
    warranty: 'Lifetime',
    stock: 4,
    rating: 4.9,
    reviewCount: 47,
    gender: 'Women',
    occasion: ['Wedding', 'Festival', 'Traditional'],
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    hasSizeGuide: false,
    sizeGuideType: null,
    highlights: ['Earring + Necklace Set', 'Ruby & Emerald Stones', 'Temple Motifs', '22K Gold'],
  },
  {
    id: '6',
    slug: 'custom-engagement-ring',
    name: 'Custom Engagement Ring',
    category: 'Rings',
    categorySlug: 'rings',
    description: 'Design your dream engagement ring with our master craftsmen.',
    longDescription:
      'Create a one-of-a-kind engagement ring that tells your unique love story. Choose from our selection of certified diamonds, precious metals, and settings. Our master craftsmen will bring your vision to life with meticulous attention to detail.',
    price: 85000,
    images: [img(33343007), img(14058109), img(30541185), img(12290109)],
    metal: 'Platinum / 18K Gold',
    purity: 'Custom',
    stone: 'Diamond (Custom)',
    weight: 'Custom',
    certification: 'GIA Certified',
    warranty: 'Lifetime',
    stock: 99,
    rating: 5.0,
    reviewCount: 73,
    gender: 'Women',
    occasion: ['Engagement', 'Wedding'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    hasSizeGuide: true,
    sizeGuideType: 'ring',
    highlights: ['Fully Customizable', 'GIA Certified Diamond', 'Free Design Consultation', 'Lifetime Warranty'],
  },
  {
    id: '7',
    slug: 'vintage-gold-chain',
    name: 'Vintage Gold Chain',
    category: 'Chains',
    categorySlug: 'chains',
    description: 'Classic 22K gold chain with intricate link design.',
    longDescription:
      'The Vintage Gold Chain features a timeless link design crafted in 22K gold. Its versatile style makes it perfect for everyday wear or special occasions. The chain can be worn alone or paired with your favorite pendant.',
    price: 75000,
    originalPrice: 90000,
    images: [img(3641059), img(3641056), img(31728371), img(5737285)],
    metal: '22K Gold',
    purity: '22K (916)',
    stone: 'None',
    weight: '12g',
    certification: 'BIS Hallmarked',
    warranty: 'Lifetime',
    stock: 12,
    rating: 4.6,
    reviewCount: 89,
    gender: 'Unisex',
    occasion: ['Casual', 'Daily Wear'],
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    hasSizeGuide: true,
    sizeGuideType: 'chain',
    highlights: ['22K Hallmarked Gold', 'Versatile Design', 'Multiple Lengths Available', 'Daily Wear'],
  },
  {
    id: '8',
    slug: 'diamond-tennis-bracelet',
    name: 'Diamond Tennis Bracelet',
    category: 'Bracelets',
    categorySlug: 'bracelets',
    description: 'Stunning diamond tennis bracelet in 18K white gold.',
    longDescription:
      'The Diamond Tennis Bracelet features a continuous line of brilliant-cut diamonds set in 18K white gold. This timeless piece adds effortless elegance to any outfit, from casual to formal.',
    price: 155000,
    images: [img(3641056), img(3641059), img(31728371), img(5737285)],
    metal: '18K White Gold',
    purity: '18K (750)',
    stone: 'Natural Diamond',
    weight: '10g',
    certification: 'GIA Certified',
    warranty: 'Lifetime',
    stock: 6,
    rating: 4.9,
    reviewCount: 54,
    gender: 'Women',
    occasion: ['Party', 'Anniversary', 'Gift'],
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    hasSizeGuide: true,
    sizeGuideType: 'bracelet',
    highlights: ['GIA Certified Diamonds', '18K White Gold', 'Secure Clasp', 'Lifetime Warranty'],
  },
  {
    id: '9',
    slug: 'silver-anklet-payal',
    name: 'Silver Anklet Payal',
    category: 'Anklets',
    categorySlug: 'anklets',
    description: 'Traditional silver anklet with delicate ghungroos.',
    longDescription:
      'The Silver Anklet Payal features traditional Indian design with delicate ghungroos that create a gentle musical sound. Crafted in premium sterling silver, this anklet is both comfortable and beautiful.',
    price: 8500,
    originalPrice: 12000,
    images: [img(20626511), img(8886971), img(8887000), img(10976654)],
    metal: 'Sterling Silver',
    purity: '92.5%',
    stone: 'None',
    weight: '15g',
    certification: 'BIS Hallmarked',
    warranty: '2 Years',
    stock: 25,
    rating: 4.5,
    reviewCount: 112,
    gender: 'Women',
    occasion: ['Traditional', 'Daily Wear', 'Festival'],
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    hasSizeGuide: true,
    sizeGuideType: 'anklet',
    highlights: ['Sterling Silver', 'Traditional Ghungroos', 'Comfortable Fit', 'Adjustable'],
  },
  {
    id: '10',
    slug: 'emerald-pendant-necklace',
    name: 'Emerald Pendant Necklace',
    category: 'Pendants',
    categorySlug: 'pendants',
    description: 'Lush green emerald pendant in 22K gold setting.',
    longDescription:
      'The Emerald Pendant Necklace features a vibrant Colombian emerald set in an intricate 22K gold setting. The pendant hangs from a delicate gold chain, creating an elegant statement piece.',
    price: 95000,
    images: [img(36650259), img(5820156), img(37485302), img(15622999)],
    metal: '22K Gold',
    purity: '22K (916)',
    stone: 'Colombian Emerald',
    weight: '8g',
    certification: 'GIA Certified',
    warranty: 'Lifetime',
    stock: 8,
    rating: 4.8,
    reviewCount: 41,
    gender: 'Women',
    occasion: ['Party', 'Gift', 'Anniversary'],
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    hasSizeGuide: true,
    sizeGuideType: 'necklace',
    highlights: ['Colombian Emerald', '22K Gold Setting', 'GIA Certified', 'Adjustable Chain'],
  },
  {
    id: '11',
    slug: 'mens-gold-kada',
    name: "Men's Gold Kada",
    category: 'Mens Jewelry',
    categorySlug: 'mens-jewelry',
    description: 'Bold 22K gold kada designed for men.',
    longDescription:
      "The Men's Gold Kada is a statement piece crafted in 22K gold with a bold, masculine design. The kada features intricate engraving and a comfortable fit, making it perfect for daily wear or special occasions.",
    price: 135000,
    originalPrice: 155000,
    images: [img(37485309), img(37485307), img(8887000), img(20626511)],
    metal: '22K Gold',
    purity: '22K (916)',
    stone: 'None',
    weight: '35g',
    certification: 'BIS Hallmarked',
    warranty: 'Lifetime',
    stock: 10,
    rating: 4.7,
    reviewCount: 38,
    gender: 'Men',
    occasion: ['Daily Wear', 'Festival', 'Gift'],
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    hasSizeGuide: true,
    sizeGuideType: 'bangle',
    highlights: ['22K Hallmarked Gold', 'Bold Masculine Design', 'Comfortable Fit', 'Daily Wear'],
  },
  {
    id: '12',
    slug: 'kids-gold-bangle',
    name: 'Kids Gold Bangle',
    category: 'Kids Collection',
    categorySlug: 'kids-collection',
    description: 'Adorable 22K gold bangle for children.',
    longDescription:
      'The Kids Gold Bangle is a charming piece crafted in 22K gold with playful, child-friendly designs. The bangle features a secure clasp and adjustable fit to grow with your little one.',
    price: 25000,
    images: [img(37485309), img(37485307), img(8886971), img(8887000)],
    metal: '22K Gold',
    purity: '22K (916)',
    stone: 'None',
    weight: '6g',
    certification: 'BIS Hallmarked',
    warranty: 'Lifetime',
    stock: 20,
    rating: 4.6,
    reviewCount: 67,
    gender: 'Kids',
    occasion: ['Birthday', 'Gift', 'Traditional'],
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    hasSizeGuide: true,
    sizeGuideType: 'bangle',
    highlights: ['22K Gold', 'Child-Safe Design', 'Adjustable Fit', 'Perfect Gift'],
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    productId: '1',
    author: 'Priya Sharma',
    rating: 5,
    date: '2026-08-15',
    title: 'Absolutely stunning!',
    content: 'The diamond is brilliant and the craftsmanship is exceptional. My wife loves it!',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=100',
  },
  {
    id: 'r2',
    productId: '1',
    author: 'Rajesh Kumar',
    rating: 5,
    date: '2026-07-22',
    title: 'Worth every rupee',
    content: 'The GIA certification gave me confidence. The ring exceeded our expectations.',
    avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=100',
  },
  {
    id: 'r3',
    productId: '1',
    author: 'Anita Reddy',
    rating: 4,
    date: '2026-06-10',
    title: 'Beautiful ring',
    content: 'Gorgeous ring but shipping took a bit longer than expected. Still worth the wait.',
    avatar: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=100',
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: 'b1',
    slug: 'diamond-buying-guide',
    title: 'Diamond Buying Guide: Everything You Need to Know',
    excerpt:
      'Learn about the 4Cs, certification, and how to choose the perfect diamond for your special occasion.',
    content:
      'When purchasing a diamond, understanding the 4Cs—Cut, Color, Clarity, and Carat weight—is essential. The Cut determines the diamond\'s brilliance, Color ranges from D (colorless) to Z, Clarity measures inclusions, and Carat weight affects size. Always look for GIA certification to ensure quality and authenticity.',
    author: 'Aurelia Expert',
    date: '2026-08-01',
    image: 'https://images.pexels.com/photos/31728371/pexels-photo-31728371.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Guides',
    readTime: '8 min read',
  },
  {
    id: 'b2',
    slug: 'gold-purity-explained',
    title: 'Gold Purity Explained: 18K vs 22K vs 24K',
    excerpt:
      'Understand the differences between gold purity levels and choose the right one for your jewelry.',
    content:
      'Gold purity is measured in karats. 24K gold is 99.9% pure—soft and ideal for investment. 22K gold is 91.6% pure—perfect for jewelry with a rich color. 18K gold is 75% pure—durable and great for diamond settings. Understanding BIS hallmarks ensures you get authentic gold.',
    author: 'Aurelia Expert',
    date: '2026-07-15',
    image: 'https://images.pexels.com/photos/37485307/pexels-photo-37485307.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Education',
    readTime: '6 min read',
  },
  {
    id: 'b3',
    slug: 'jewelry-care-tips',
    title: 'Jewelry Care Tips: Keep Your Pieces Shining',
    excerpt:
      'Simple tips to maintain the beauty and longevity of your precious jewelry pieces.',
    content:
      'Store jewelry separately to avoid scratches. Clean with mild soap and warm water. Avoid contact with chemicals, perfumes, and cosmetics. Have your jewelry professionally inspected annually. For diamond jewelry, use a soft brush to clean under the settings.',
    author: 'Aurelia Expert',
    date: '2026-06-20',
    image: 'https://images.pexels.com/photos/10976654/pexels-photo-10976654.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'Care Tips',
    readTime: '5 min read',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    name: 'Priya & Arjun',
    location: 'Chennai, Tamil Nadu',
    rating: 5,
    content:
      'Our bridal jewelry from Aurelia was beyond perfect. The craftsmanship and attention to detail made our wedding even more special. The temple necklace was a showstopper!',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 't2',
    name: 'Meena Krishnan',
    location: 'Bengaluru, Karnataka',
    rating: 5,
    content:
      'I designed a custom engagement ring and the team brought my vision to life flawlessly. The GIA certification gave me complete peace of mind. Truly exceptional service.',
    avatar: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 't3',
    name: 'Vikram Reddy',
    location: 'Hyderabad, Telangana',
    rating: 5,
    content:
      'The diamond tennis bracelet I gifted my wife for our anniversary is stunning. The quality and brilliance are unmatched. Aurelia has earned a customer for life.',
    avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
  {
    id: 't4',
    name: 'Lakshmi Nair',
    location: 'Kochi, Kerala',
    rating: 5,
    content:
      'The pearl drop earrings are my everyday favorite. Lightweight, elegant, and versatile. The packaging was luxurious and delivery was prompt. Highly recommend!',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=200',
  },
];

export const faqItems: FAQItem[] = [
  {
    id: 'f1',
    question: 'Is all jewelry certified?',
    answer:
      'Yes, all our jewelry comes with proper certification. Diamond jewelry includes GIA certification, and all gold items are BIS hallmarked. You receive the original certificates with your purchase.',
  },
  {
    id: 'f2',
    question: 'What is the return policy?',
    answer:
      'We offer a 14-day return policy on all non-customized jewelry. Items must be unworn and in original condition with all packaging and certificates. Custom-designed pieces are non-returnable.',
  },
  {
    id: 'f3',
    question: 'How long does shipping take?',
    answer:
      'In-stock items ship within 2-3 business days and arrive in 5-7 business days. Custom designs take 3-4 weeks. All shipments are fully insured and require signature on delivery.',
  },
  {
    id: 'f4',
    question: 'Can I order custom jewelry?',
    answer:
      'Absolutely! Visit our Custom Design page to upload inspiration, choose your metal, stone, and budget. Our master craftsmen will create a unique piece just for you with a free consultation.',
  },
  {
    id: 'f5',
    question: 'Which payment methods are accepted?',
    answer:
      'We accept UPI, Visa, Mastercard, RuPay, Net Banking, and EMI options. All transactions are secured with 256-bit SSL encryption for your safety.',
  },
  {
    id: 'f6',
    question: 'How do I track my order?',
    answer:
      'Once your order ships, you will receive a tracking number via email and SMS. You can also track your order anytime using our Order Tracking page with your order number.',
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.categorySlug === categorySlug);
}

export function getRelatedProducts(product: Product, count = 4): Product[] {
  return products
    .filter((p) => p.id !== product.id && p.categorySlug === product.categorySlug)
    .slice(0, count);
}

export function getReviewsByProduct(productId: string): Review[] {
  return reviews.filter((r) => r.productId === productId);
}
